### ISSUE TITLE
Dashboard script files path

### ISSUE THREAD

**Issue by sergioasantiago** [opendiffy/diffy#20]
In order to use the Dashboard behind an api gateway, that forward the path to the underneath service, we should be able to specify in the dashboard html the apiRoot, and prefix it to the scripts (*.js/*.css) files path.

In our use case, we have the apigateway that proxy the requests and redirect it to the underneath service. We have configured the apiRoot variable to /diffyservice, which works ok for the calls made by the js scripts, but the Dashboard html is not reflecting the same behaviour.

I suggest to add the {{apiRoot}} to the scripts path in order to fix it.

I can create the PR if needed.

**Comment by puneetkhanduri** [comment]
@sergioasantiago : The apiRoot parameter was originally meant for Diffy UI development because redeploying the server is pretty slow :)
That said, we no longer use that development flow so happy to repurpose it to the API gateway use case. I want to make sure that the change actually solves your problem so could you please try deploying the apigateway branch I have pushed to master.

**Comment by sergioasantiago** [comment]
Hi @puneetkhanduri this is exactly the change that I have done in my fork in order to make it work. I appreciate your prompt answer. LGTM

PS: quick question, why there are 2 projects (opendiffy/diffy and twitter/diffy). In case of issues, which project should I address to?

Thanks

**Comment by puneetkhanduri** [comment]
This is the one to follow. The other one has some legacy Twitter-specific logic. Eventually, we hope those legacy services will be deprecated at Twitter and we will be able to move everyone to this project.

**Comment by sergioasantiago** [comment]
Is it possible to have this same behaviour, but for /admin ?
