### ISSUE TITLE
Request Logging

### ISSUE THREAD

**Issue by piabinder** [opendiffy/diffy#46]
Hi,
we want to use diffy in our project.
For this we need an additional function to log all incoming requests. 
Does diffy has this function or can it be implemented?

**Comment by puneetkhanduri** [comment]
https://github.com/opendiffy/diffy/blob/master/README.md#code-of-conduct

**Comment by zellerr** [comment]
Hi Puneet,
sorry für the anonymous feature request. We just got our company account created and are eager to getting more involved in open source projects... 
Our current plan is to use Diffy in the context of refactoring / rewriting a big monolithic application which only provides a handful of automated tests. Diffy's features seem to be a perfect match for our use case :-)
In order to identify requests that are not used anymore by the clients, we would love to see

**Comment by zellerr** [comment]
Hi Puneet,
sorry for the anonymous feature request. We just got our company account created and are eager to getting more involved in open source projects...
Our current plan is to use Diffy in the context of refactoring / rewriting a big monolithic application which only provides a handful of automated tests. Diffy's features seem to be a perfect match for our use case :-)
In order to identify requests that are not used anymore by the clients, we would love the requests to be logged. Of course we could use another proxy for that purpose but it would make things quite complex. 
So it would be really nice if you could elaborate if you have plans on including this functionality? Potentially we are ready to get ours hands on as well, however we are not into Scala right now.

**Comment by puneetkhanduri** [comment]
Diffy produces a ```differences.log``` file that tracks requests processed by Diffy. Each line in the log represents one request and I can add the name of the corresponding endpoint to each line.

Parsing the log will allow you to discover all the endpoints that were processed by Diffy. Would this be sufficient for your current use case?

**Comment by zellerr** [comment]
Thank you for your quick reply. 

We just reviewed the `differences.log` file that you pointed out and came to the conclusion that all information we want to track is already provided :-)

Thanks for the very helpful hint (and for this great project).

**Comment by puneetkhanduri** [comment]
@zellerr : We are reviewing our roadmap for Diffy and are gathering user stories and feature requests. Please feel free to book a 30 minute meeting on [my calendar](https://calendly.com/pzdk) if you or team may be interested.

**Comment by zellerr** [comment]
@puneetkhanduri Thanks for the info.
Currently, we are still laying the foundations for the renovation of our monolith and do not yet know what new features that might be useful. However, I am sure we will come back to you once we gathered some experiences with Diffy.
So long keep up the great work!

**Comment by puneetkhanduri** [comment]
@zellerr Best of luck for your migration from your monolith. Do write about your experience and where Diffy did a good job and where it could have done better. We love reading such stories from our users.

**Comment by zellerr** [comment]
@puneetkhanduri Thank you. We will keep you posted about how we get along with Diffy in the stormy seas of our migration mission :-)
